### ISSUE TITLE
[JOSS Review] Issue with `rasterize_gdf_hd` function in notebooks examples

### ISSUE THREAD

**Issue by samuelduchesne** [AlexanderJuestel/pyheatdemand#31]
**Describe the bug**
TypeError returned in cell 21 "rasterizing vector data": `TypeError: rasterize_gdf_hd() got an unexpected keyword argument 'flip_raster'`

**To Reproduce**
1. Go to :
 - [ ] `docs/source/notebooks/06_Processing_Data_Type_III_Point_Coordinates.ipynb`
 - [ ] `docs/source/notebooks/07_Processing_Data_Type_III_Point_Data_Addresses.ipynb`
 - [ ] `docs/source/notebooks/08_Processing_Data_Type_IV_Vector_Polygons.ipynb`
 - [ ] `docs/source/notebooks/13_Processing_and_merging_heat_demand_data_for_NRW.ipynb`
3. Click `run all`
- [ ] Without the missing `flip_raster` function parameter, the rasters also looked flipped when rendered

**Comment by AlexanderJuestel** [comment]
Thanks for reporting that. I will have a look!

**Comment by AlexanderJuestel** [comment]
@samuelduchesne just forgot to push that. It was added in now https://github.com/AlexanderJuestel/pyheatdemand/commit/cc810de5204ec317ea348d471426b2ffd9533286
