### ISSUE TITLE
[JOSS Review] Small typo

### ISSUE THREAD

**Issue by samuelduchesne** [AlexanderJuestel/pyheatdemand#32]
Stumbled upon this typo: double `of of`

https://github.com/AlexanderJuestel/pyheatdemand/blob/4bdc7718a5ea82c48325377d52cf068ca110b3d0/pyheatdemand/processing.py#L139

**Comment by AlexanderJuestel** [comment]
@samuelduchesne, this was fixed in https://github.com/AlexanderJuestel/pyheatdemand/commit/7ec87b7c9db736ffed44025ef4b98e1d1acd8a5a
