### ISSUE TITLE
[JOSS Review] Consider using `black` (or similar) to format the codebase

### ISSUE THREAD

**Issue by samuelduchesne** [AlexanderJuestel/pyheatdemand#33]
I generally recommend `python` developers to use a strict code formatter such as `[black](https://black.readthedocs.io/en/stable/)` to help the development process. The idea is simple: if the code is always formatted the same way, you are only committing actual code changes instead of formatting changes (black spaces, tabs, etc.)

**Comment by AlexanderJuestel** [comment]
@samuelduchesne `processing.py` was formatted using black in https://github.com/AlexanderJuestel/pyheatdemand/commit/d133e51f9dc5b5111f3c1a1bde62758e8a0534d2 

Thanks for the suggestion!

**Comment by samuelduchesne** [comment]
Great, you can also add `black` to your pyproject.toml if you want to specify a different configuration

**Comment by samuelduchesne** [comment]
Also, you should format all the codebase with `black` not just the `processing.py` file - ie run `black .` from the root of the repo

**Comment by AlexanderJuestel** [comment]
> Also, you should format all the codebase with `black` not just the `processing.py` file - ie run `black .` from the root of the repo

Codebase was formatted in https://github.com/AlexanderJuestel/pyheatdemand/commit/776ce06be253c47858ab5bf908471dbd6c4bdfbe

**Comment by AlexanderJuestel** [comment]
> Great, you can also add `black` to your pyproject.toml if you want to specify a different configuration

I added black to the pyproject.toml in https://github.com/AlexanderJuestel/pyheatdemand/commit/f562220b385a69d234f878d6b00346cfc791aff4
