### ISSUE TITLE
[JOSS Review ] Use a "numpy.random.Generator" here instead of this legacy function

### ISSUE THREAD

**Issue by samuelduchesne** [AlexanderJuestel/pyheatdemand#34]
- [ ] https://github.com/AlexanderJuestel/pyheatdemand/blob/4bdc7718a5ea82c48325377d52cf068ca110b3d0/pyheatdemand/processing.py#L380-L382
- [ ] https://github.com/AlexanderJuestel/pyheatdemand/blob/496ce2216bbf78db8080a5cb8ed5feb800e91be2/test/test_processing.py#L675
- [ ] https://github.com/AlexanderJuestel/pyheatdemand/blob/496ce2216bbf78db8080a5cb8ed5feb800e91be2/test/test_processing.py#L679
- [ ] https://github.com/AlexanderJuestel/pyheatdemand/blob/496ce2216bbf78db8080a5cb8ed5feb800e91be2/test/test_processing.py#L712
- [ ] https://github.com/AlexanderJuestel/pyheatdemand/blob/496ce2216bbf78db8080a5cb8ed5feb800e91be2/test/test_processing.py#L716
- [ ] https://github.com/AlexanderJuestel/pyheatdemand/blob/496ce2216bbf78db8080a5cb8ed5feb800e91be2/test/test_processing.py#L771
- [ ] https://github.com/AlexanderJuestel/pyheatdemand/blob/496ce2216bbf78db8080a5cb8ed5feb800e91be2/test/test_processing.py#L775
- [ ] https://github.com/AlexanderJuestel/pyheatdemand/blob/496ce2216bbf78db8080a5cb8ed5feb800e91be2/test/test_processing.py#L805
- [ ] https://github.com/AlexanderJuestel/pyheatdemand/blob/496ce2216bbf78db8080a5cb8ed5feb800e91be2/test/test_processing.py#L809

## Why?

See: https://rules.sonarsource.com/python/type/Code%20Smell/RSPEC-6711/

## Solution
To fix this issue, replace usages of numpy.random.RandomState to numpy.random.Generator.

```python
val = np.random.uniform(
  0, 
  0.001,
  size=data.shape
).astype(np.float32)
```

becomes:
```python
generator = np.random.default_rng(42)  # set seed number for reproducibility
val = generator.uniform(
  0,
  0.001,
  size=data.shape
).astype(np.float32)
```

**Comment by AlexanderJuestel** [comment]
@samuelduchesne all instances were fixed and I also formatted the file using black in https://github.com/AlexanderJuestel/pyheatdemand/commit/46b974e2437099823b95a257b350992f209e1175
